### ISSUE TITLE
Unique flag in state is always true

### ISSUE THREAD

**Issue by SakulK** [tutorialhorizon/react-tagged-input#15]
In _validateAndTag uniquness flag is checked in the state (s.unique) and that state is always true from what I can tell:
```javascript
unique: this.props.unique || true
```
There doesn't seem to be any code that changes that state either, so shouldn't it just use the prop?

**Comment by thmain** [comment]
@SakulK Good catch. That makes perfect sense. I have fixed it in the latest commit along with a bug that was arising due to a wrong 'key' property being set for each tag in case you were experiencing it. It only happened if you set unique to false.
All is well now!
