### ISSUE TITLE
Case Sensitivity 

### ISSUE THREAD

**Issue by Terri-Lynn** [tutorialhorizon/react-tagged-input#17]
Right now I'm using your module and have "tags" equal to a state variable.  onBeforeAddTag I check to see if it's one of the acceptable values, and add it in the appropriate case  IE helLO input becomes Hello tag.  So if someone types in hello or hellO etc after, I want the key that matches that to highlight yellow ignoring the case so the user has some type of indication as to why their key isn't getting added.

Would you be open to having a prop like isCaseSensitive so case doesn't matter on validateAndTag?  Or be open to a global method that is somewhat equivalent to _validateAndTag?  Or is there a way to do this already that I'm not seeing?  Right now my work around to get this to work is on onBeforeAddTag I'm grabbing myTag.refs.tags.state.tags.indexOf(myTag.refs.tags.getEnteredText()) and if a value comes when onAddFlag is called I call myTag.refs.flags._validateAndTag(currentInput) so the proper word is highlighted yellow.

**Comment by thmain** [comment]
@Terri-Lynn you can install the latest version of the package to satisfy your requirement.
