### ISSUE TITLE
Component mutates array provided in tags prop

### ISSUE THREAD

**Issue by alistairjcbrown** [tutorialhorizon/react-tagged-input#22]
When an array is passed in as a prop for `tags`, it is mutated. This has a the side effect of changing the parent component's state without triggering an update.
See below for example code and console output.

#### Potential Fix

A simple fix would be to use `Array.prototype.concat` to make a copy of the tags array from `this.props` when setting the initial state.

```js
getInitialState: function () {
  return {
    tags: [].concat(this.props.tags) || [],
    currentInput: null
  };
},
```

https://github.com/tutorialhorizon/react-tagged-input/blob/e155c0f34738a5f4a733cc48704a6fc80a0ddf50/src/TaggedInput.jsx#L70

---

#### Example:

```js
var MyComponent = React.createClass({
  getInitialState() {
    return { tags: ['foo'] };
  },

  onAddTag(value) {
    console.log('onAddTag', value, this.state.tags);
  },

  onRemoveTag(value) {
    console.log('onRemoveTag', value, this.state.tags);
  },

  render() {
    return (
      <div>
        <TaggedInput tags={this.state.tags}
                     onAddTag={this.onAddTag}
                     onRemoveTag={this.onRemoveTag} />
      </div>
    );
  }
});
```

__Console output__

```
> onAddTag bar ["foo", "bar"]
> onRemoveTag foo ["bar"]
```

Given that `MyComponent` never updates its state, the values of `this.state.tags` should never change. However, the console output above shows that `TaggedInput` has modified the tags array from the state of `MyComponent`.

**Comment by thmain** [comment]
@alistairjcbrown Thanks for reporting the issue!
Would you like to send a PR for the same?

**Comment by alistairjcbrown** [comment]
@thmain No worries - thanks for the great component. I'm using it in a side project at the moment and so I didn't forget, I fired up a few issues.
I'll see about getting some PRs up tonight for them :+1:

**Comment by thmain** [comment]
Fixed!
