### ISSUE TITLE
Update parameters in `onAddTag` and `onRemoveTag` to also provide full array of tags

### ISSUE THREAD

**Issue by alistairjcbrown** [tutorialhorizon/react-tagged-input#23]
I'd love to be able to retrieve the list of all tags when the contents of the input changes.

As it stands, in an application, the component wrapping the tagged input has to manage a list of tags too; adding to its state when the `onAddTag` callback is called and removing from its state when the `onRemoveTag` callback is called.
Instead, it would be nicer to be able to simply update the state with the current list of all tags in the input.

Perhaps `onAddTag` and `onRemoveTag` could return the full list of tags, as well as the tag has just been added or removed?

#### Example:

```js
var MyComponent = React.createClass({
  getInitialState() {
    return { tags: ['foo'] };
  },

  updateTags(tagChanged, tags) {
    this.setState({ tags: tags });
  },

  render() {
    return (
      <div>
        <TaggedInput tags={this.state.tags}
                     onAddTag={this.updateTags}
                     onRemoveTag={this.updateTags} />
      </div>
    );
  }
});
```

**Comment by thmain** [comment]
Sounds like a reasonable thing to do. I will accept a PR if you'd like to make the change.
I have added a few tests to the repo but the project isint setup for CI yet. You will need to update the tests for this change. You can run the tests using `npm run test`.

**Comment by thmain** [comment]
@alistairjcbrown Its done.

**Comment by alistairjcbrown** [comment]
@thmain Fantastic, thank you! :+1:
