### ISSUE TITLE
Built version of TaggedInput

### ISSUE THREAD

**Issue by alistairjcbrown** [tutorialhorizon/react-tagged-input#24]
As a third-party library, I just want to be able to `require` the `react-tagged-input`, without having to consider how it is built by the author.
However, as this component is JSX, it's not as simple as just pulling it in. For my needs, I have to update my webpack config and jest preprocessor script to include `react-tagged-input` as an allowed `node_modules` library to be included as part of the build.

Instead, would it be possible to generate a `dist/TaggedInput.js` file (which is just pure JS), to which the `package.json` file can point? You could do this as a grunt build task.

This allows users of your library to `require` without any additional steps, but also allows you as the author to write the library however you see fit (eg. using coffeescript, splitting into multiple separate files in the `src` directory) and expose a consistent built file for use.

**Comment by thmain** [comment]
Very valid point. I will probably get to it shortly. I am open to accepting a PR if you'd like to make the change.

**Comment by alistairjcbrown** [comment]
This works for me with `v0.0.14` when pulling into a project and without needing to transpile.
