### ISSUE TITLE
`onAddTag` called even when `onBeforeAddTag` returns false

### ISSUE THREAD

**Issue by alistairjcbrown** [tutorialhorizon/react-tagged-input#25]
Returning `false` from `onBeforeAddTag` only prevents the tag from being added to the tags array; the `onAddTag` callback is still called, so any wrapping component will expect that the tag has been added (though it hasn't).
https://github.com/tutorialhorizon/react-tagged-input/blob/e155c0f34738a5f4a733cc48704a6fc80a0ddf50/src/TaggedInput.jsx#L281-L283

This is inconsistent with `onRemoveTag` and `onBeforeRemoveTag`, where returning `false` from `onBeforeRemoveTag` prevents the tag from being removed and the `onRemoveTag` callback from being called.

**Comment by thmain** [comment]
Good catch. I am inclined to making the onBeforeAddTag behave the same way as onBeforeRemove tag. Will update it soon.
